MODEL:
  META_ARCHITECTURE: "GeneralizedRCNN"
  RPN_ONLY: True
  RETINANET_ON: True
  BACKBONE:
    CONV_BODY: "MOBILENETV2-FPN-RETINANET"
  MOBILENET:
    WIDTH_MULT: 1.0
    LAST_CHANNELS: 512
    OUT_CHANNELS: 64 
   RPN:
    USE_FPN: True
    FG_IOU_THRESHOLD: 0.5
    BG_IOU_THRESHOLD: 0.4
    ANCHOR_STRIDE: (4, 8, 16, 32, 64)
    PRE_NMS_TOP_N_TRAIN: 2000
    PRE_NMS_TOP_N_TEST: 1000
    POST_NMS_TOP_N_TEST: 1000
    FPN_POST_NMS_TOP_N_TEST: 1000
  ROI_HEADS:
    USE_FPN: True
    BATCH_SIZE_PER_IMAGE: 256
  ROI_BOX_HEAD:
    POOLER_RESOLUTION: 7
    POOLER_SCALES: (0.25, 0.125, 0.0625, 0.03125)
    POOLER_SAMPLING_RATIO: 2
    FEATURE_EXTRACTOR: "FPN2MLPFeatureExtractor"
    PREDICTOR: "FPNPredictor"
    NUM_CLASSES: 2
  RETINANET:
    NUM_CLASSES: 2
    SCALES_PER_OCTAVE: 3
    OCTAVE: 2.0
    STRADDLE_THRESH: -1
    ANCHOR_SIZES: (32, 64, 128)
    ANCHOR_STRIDES: (8, 16, 32)
    NUM_CONVS: 2 
    FG_IOU_THRESHOLD: 0.5
    BG_IOU_THRESHOLD: 0.4
    ASPECT_RATIOS: (0.8, 1.5, 2.5, 3.5)
    NMS_TH: 0.5
    BBOX_REG_WEIGHT: 1.0
    PRIOR_PROB: 0.02
FREEANCHOR:
  FREEANCHOR_ON: True
  PRE_ANCHOR_TOPK: 50
  BBOX_THRESHOLD: 0.6
  BBOX_REG_WEIGHT: 0.75
  FOCAL_LOSS_ALPHA: 0.5
  FOCAL_LOSS_GAMMA: 2.0
DATASETS:
  TRAIN: ("coco_2014_person_val",)
  TEST: ("coco_2014_person_val",)
INPUT:
  MIN_SIZE_TRAIN: (320, 352, 384, 416, 448, 480, 512, 544, 576, 608, 640, 672, 704, 736, 768)
  MAX_SIZE_TRAIN: 1333
  MIN_SIZE_TEST: 512
  MAX_SIZE_TEST: 1333
DATALOADER:
  SIZE_DIVISIBILITY: 32
SOLVER:
  BASE_LR: 0.01
  WEIGHT_DECAY: 0.0001
  STEPS: (160000, 180000)
  MAX_ITER: 200000
  WARMUP_FACTOR: 0.0001
  WARMUP_ITERS: 1000 
  IMS_PER_BATCH: 8
OUTPUT_DIR: ./temp
